const scores = [
    {
        id: 1,
        team: 'varsity',
        ehs: 'Emerson',
        opponent: 'McKinney',
        ehsFinalScore: '',
        opponentFinalScore: '',
        ehsScore: '0',
        opponentScore: '0',
        final: false,
        date: '2025-08-29',
        qtr: ' ',
        timeInQtr: ' ',
        comment: 'Add who scored and how.'
    },

    {
        id: 2,
        team: 'varsity',
        ehs: 'Emerson',
        opponent: 'Reedy',
        ehsFinalScore: '',
        opponentFinalScore: '',
        ehsScore: '0',
        opponentScore: '0',
        final: false,
        date: '2025-09-04',
        qtr: ' ',
        timeInQtr: ' ',
        comment: 'Add who scored and how.'
    },

    {
        id: 3,
        team: 'varsity',
        ehs: 'Emerson',
        opponent: 'Walnut Grove',
        ehsFinalScore: '',
        opponentFinalScore: '',
        ehsScore: '0',
        opponentScore: '0',
        final: false,
        date: '2025-09-12',
        qtr: ' ',
        timeInQtr: ' ',
        comment: 'Add who scored and how.'
    },

    {
        id: 4,
        team: 'varsity',
        ehs: 'Emerson',
        opponent: 'Denison',
        ehsFinalScore: '',
        opponentFinalScore: '',
        ehsScore: '0',
        opponentScore: '0',
        final: false,
        date: '2025-09-19',
        qtr: ' ',
        timeInQtr: ' ',
        comment: 'Add who scored and how.'
    },

    {
        id: 5,
        team: 'varsity',
        ehs: 'Emerson',
        opponent: 'Memorial',
        ehsFinalScore: '',
        opponentFinalScore: '',
        ehsScore: '0',
        opponentScore: '0',
        final: false,
        date: '2025-09-26',
        qtr: ' ',
        timeInQtr: ' ',
        comment: 'Add who scored and how.'
    },

    {
        id: 6,
        team: 'varsity',
        ehs: 'Emerson',
        opponent: 'Liberty',
        ehsFinalScore: '',
        opponentFinalScore: '',
        ehsScore: '0',
        opponentScore: '0',
        final: false,
        date: '2025-10-03',
        qtr: ' ',
        timeInQtr: ' ',
        comment: 'Add who scored and how.'
    },

    {
        id: 7,
        team: 'varsity',
        ehs: 'Emerson',
        opponent: 'Anna',
        ehsFinalScore: '',
        opponentFinalScore: '',
        ehsScore: '0',
        opponentScore: '0',
        final: false,
        date: '2025-10-10',
        qtr: ' ',
        timeInQtr: ' ',
        comment: 'Add who scored and how.'
    },

    {
        id: 8,
        team: 'varsity',
        ehs: 'Emerson',
        opponent: 'LoveJoey',
        ehsFinalScore: '',
        opponentFinalScore: '',
        ehsScore: '0',
        opponentScore: '0',
        final: false,
        date: '2025-10-16',
        qtr: ' ',
        timeInQtr: ' ',
        comment: 'Add who scored and how.'
    },

    {
        id: 9,
        team: 'varsity',
        ehs: 'Emerson',
        opponent: 'Melissa',
        ehsFinalScore: '',
        opponentFinalScore: '',
        ehsScore: '0',
        opponentScore: '0',
        final: false,
        date: '2025-10-24',
        qtr: ' ',
        timeInQtr: ' ',
        comment: 'Add who scored and how.'
    },

    {
        id: 10,
        team: 'varsity',
        ehs: 'Emerson',
        opponent: 'Independence',
        ehsFinalScore: '',
        opponentFinalScore: '',
        ehsScore: '0',
        opponentScore: '0',
        final: false,
        date: '2025-10-30',
        qtr: ' ',
        timeInQtr: ' ',
        comment: 'Add who scored and how.'
    },

    {
        id: 11,
        team: 'jv',
        ehs: 'Emerson',
        opponent: 'McKinney',
        ehsFinalScore: '',
        opponentFinalScore: '',
        ehsScore: '0',
        opponentScore: '0',
        final: false,
        date: '2025-08-28',
        qtr: ' ',
        timeInQtr: ' ',
        comment: 'Add who scored and how.'
    },

    {
        id: 12,
        team: 'jv',
        ehs: 'Emerson',
        opponent: 'Reedy',
        ehsFinalScore: '',
        opponentFinalScore: '',
        ehsScore: '0',
        opponentScore: '0',
        final: false,
        date: '2025-09-03',
        qtr: ' ',
        timeInQtr: ' ',
        comment: 'Add who scored and how.'
    },

    {
        id: 13,
        team: 'jv',
        ehs: 'Emerson',
        opponent: 'Walnut Grove',
        ehsFinalScore: '',
        opponentFinalScore: '',
        ehsScore: '0',
        opponentScore: '0',
        final: false,
        date: '2025-09-11',
        qtr: ' ',
        timeInQtr: ' ',
        comment: 'Add who scored and how.'
    },

    {
        id: 14,
        team: 'jv',
        ehs: 'Emerson',
        opponent: 'Denison',
        ehsFinalScore: '',
        opponentFinalScore: '',
        ehsScore: '0',
        opponentScore: '0',
        final: false,
        date: '2025-09-18',
        qtr: ' ',
        timeInQtr: ' ',
        comment: 'Add who scored and how.'
    },

    {
        id: 15,
        team: 'jv',
        ehs: 'Emerson',
        opponent: 'Memorial',
        ehsFinalScore: '',
        opponentFinalScore: '',
        ehsScore: '0',
        opponentScore: '0',
        final: false,
        date: '2025-09-25',
        qtr: ' ',
        timeInQtr: ' ',
        comment: 'Add who scored and how.'
    },

    {
        id: 16,
        team: 'jv',
        ehs: 'Emerson',
        opponent: 'Liberty',
        ehsFinalScore: '',
        opponentFinalScore: '',
        ehsScore: '0',
        opponentScore: '0',
        final: false,
        date: '2025-10-02',
        qtr: ' ',
        timeInQtr: ' ',
        comment: 'Add who scored and how.'
    },

    {
        id: 17,
        team: 'jv',
        ehs: 'Emerson',
        opponent: 'Anna',
        ehsFinalScore: '',
        opponentFinalScore: '',
        ehsScore: '0',
        opponentScore: '0',
        final: false,
        date: '2025-10-09',
        qtr: ' ',
        timeInQtr: ' ',
        comment: 'Add who scored and how.'
    },

    {
        id: 18,
        team: 'jv',
        ehs: 'Emerson',
        opponent: 'LoveJoey',
        ehsFinalScore: '',
        opponentFinalScore: '',
        ehsScore: '0',
        opponentScore: '0',
        final: false,
        date: '2025-10-15',
        qtr: ' ',
        timeInQtr: ' ',
        comment: 'Add who scored and how.'
    },

    {
        id: 19,
        team: 'jv',
        ehs: 'Emerson',
        opponent: 'Melissa',
        ehsFinalScore: '',
        opponentFinalScore: '',
        ehsScore: '0',
        opponentScore: '0',
        final: false,
        date: '2025-10-23',
        qtr: ' ',
        timeInQtr: ' ',
        comment: 'Add who scored and how.'
    },

    {
        id: 20,
        team: 'jv',
        ehs: 'Emerson',
        opponent: 'Independence',
        ehsFinalScore: '',
        opponentFinalScore: '',
        ehsScore: '0',
        opponentScore: '0',
        final: false,
        date: '2025-10-29',
        qtr: ' ',
        timeInQtr: ' ',
        comment: 'Add who scored and how.'
    },

        {
        id: 21,
        team: 'freshmen',
        ehs: 'Emerson',
        opponent: 'McKinney',
        ehsFinalScore: '',
        opponentFinalScore: '',
        ehsScore: '0',
        opponentScore: '0',
        final: false,
        date: '2025-08-28',
        qtr: ' ',
        timeInQtr: ' ',
        comment: 'Add who scored and how.'
    },

    {
        id: 22,
        team: 'freshmen',
        ehs: 'Emerson',
        opponent: 'Reedy',
        ehsFinalScore: '',
        opponentFinalScore: '',
        ehsScore: '0',
        opponentScore: '0',
        final: false,
        date: '2025-09-03',
        qtr: ' ',
        timeInQtr: ' ',
        comment: 'Add who scored and how.'
    },

    {
        id: 23,
        team: 'freshmen',
        ehs: 'Emerson',
        opponent: 'Walnut Grove',
        ehsFinalScore: '',
        opponentFinalScore: '',
        ehsScore: '0',
        opponentScore: '0',
        final: false,
        date: '2025-09-11',
        qtr: ' ',
        timeInQtr: ' ',
        comment: 'Add who scored and how.'
    },

    {
        id: 24,
        team: 'freshmen',
        ehs: 'Emerson',
        opponent: 'Denison',
        ehsFinalScore: '',
        opponentFinalScore: '',
        ehsScore: '0',
        opponentScore: '0',
        final: false,
        date: '2025-09-18',
        qtr: ' ',
        timeInQtr: ' ',
        comment: 'Add who scored and how.'
    },

    {
        id: 25,
        team: 'freshmen',
        ehs: 'Emerson',
        opponent: 'Memorial',
        ehsFinalScore: '',
        opponentFinalScore: '',
        ehsScore: '0',
        opponentScore: '0',
        final: false,
        date: '2025-09-25',
        qtr: ' ',
        timeInQtr: ' ',
        comment: 'Add who scored and how.'
    },

    {
        id: 26,
        team: 'freshmen',
        ehs: 'Emerson',
        opponent: 'Liberty',
        ehsFinalScore: '',
        opponentFinalScore: '',
        ehsScore: '0',
        opponentScore: '0',
        final: false,
        date: '2025-10-02',
        qtr: ' ',
        timeInQtr: ' ',
        comment: 'Add who scored and how.'
    },

    {
        id: 27,
        team: 'freshmen',
        ehs: 'Emerson',
        opponent: 'Anna',
        ehsFinalScore: '',
        opponentFinalScore: '',
        ehsScore: '0',
        opponentScore: '0',
        final: false,
        date: '2025-10-09',
        qtr: ' ',
        timeInQtr: ' ',
        comment: 'Add who scored and how.'
    },

    {
        id: 28,
        team: 'freshmen',
        ehs: 'Emerson',
        opponent: 'LoveJoey',
        ehsFinalScore: '',
        opponentFinalScore: '',
        ehsScore: '0',
        opponentScore: '0',
        final: false,
        date: '2025-10-15',
        qtr: ' ',
        timeInQtr: ' ',
        comment: 'Add who scored and how.'
    },

    {
        id: 29,
        team: 'freshmen',
        ehs: 'Emerson',
        opponent: 'Melissa',
        ehsFinalScore: '',
        opponentFinalScore: '',
        ehsScore: '0',
        opponentScore: '0',
        final: false,
        date: '2025-10-23',
        qtr: ' ',
        timeInQtr: ' ',
        comment: 'Add who scored and how.'
    },

    {
        id: 30,
        team: 'freshmen',
        ehs: 'Emerson',
        opponent: 'Independence',
        ehsFinalScore: '',
        opponentFinalScore: '',
        ehsScore: '0',
        opponentScore: '0',
        final: false,
        date: '2025-10-29',
        qtr: ' ',
        timeInQtr: ' ',
        comment: 'Add who scored and how.'
    }
]

export default scores